export function handlePlatforms(): Response {
  const platforms = [
    {
      id: 'douyin',
      name: '抖音',
      features: { video: true, images: true, audio: true },
      badge: '双路线',
      status: 'stable',
      parser: 'native-a/b',
      example: 'https://v.douyin.com/...',
    },
    {
      id: 'xiaohongshu',
      name: '小红书',
      features: { video: true, images: true, audio: false },
      badge: '原图',
      status: 'beta',
      parser: 'native',
      example: 'http://xhslink.com/...',
    },
    {
      id: 'bilibili',
      name: '哔哩哔哩',
      features: { video: true, images: false, audio: true },
      badge: '音视频分轨',
      status: 'stable',
      parser: 'native',
      example: 'https://b23.tv/...',
    },
    {
      id: 'kuaishou',
      name: '快手',
      features: { video: true, images: true, audio: false },
      badge: '原生',
      status: 'beta',
      parser: 'native',
      example: 'https://v.kuaishou.com/...',
    },
    {
      id: 'weibo',
      name: '微博',
      features: { video: true, images: true, audio: false },
      badge: 'Cookie 增强',
      status: 'beta',
      parser: 'native',
      example: 'https://weibo.com/...',
    },
    {
      id: 'tiktok',
      name: 'TikTok',
      features: { video: true, images: true, audio: true },
      badge: 'Native + Cobalt',
      status: 'beta',
      parser: 'native/cobalt',
      example: 'https://vt.tiktok.com/...',
    },
    {
      id: 'instagram',
      name: 'Instagram',
      features: { video: true, images: true, audio: false },
      badge: 'Cobalt',
      status: 'beta',
      parser: 'cobalt',
      example: 'https://www.instagram.com/reel/...',
    },
    {
      id: 'twitter',
      name: 'X (Twitter)',
      features: { video: true, images: true, audio: false },
      badge: 'Native / Cobalt',
      status: 'beta',
      parser: 'native/cobalt',
      example: 'https://x.com/.../status/...',
    },
    {
      id: 'youtube',
      name: 'YouTube',
      features: { video: true, images: false, audio: true },
      badge: 'Extended',
      status: 'extended',
      parser: 'cobalt',
      example: 'https://youtu.be/...',
    },
    { id: 'qsmusic', name: '汽水音乐', features: { video: true, images: false, audio: true }, badge: '歌曲/MV', status: 'beta', parser: 'native', example: 'https://qishui.douyin.com/...' },
    { id: 'pipixia', name: '皮皮虾', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://h5.pipix.com/...' },
    { id: 'pipigx', name: '皮皮搞笑', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://h5.pipigx.com/...' },
    { id: 'xigua', name: '西瓜视频', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://www.ixigua.com/...' },
    { id: 'huoshan', name: '火山', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://share.huoshan.com/...' },
    { id: 'weishi', name: '微视', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://isee.weishi.qq.com/...' },
    { id: 'zuiyou', name: '最右', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://share.xiaochuankeji.cn/...' },
    { id: 'quanmin', name: '度小视', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://xspshare.baidu.com/...' },
    { id: 'lishipin', name: '梨视频', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://www.pearvideo.com/detail_...' },
    { id: 'huya', name: '虎牙', features: { video: true, images: false, audio: false }, badge: '短视频', status: 'beta', parser: 'native', example: 'https://v.huya.com/...' },
    { id: 'acfun', name: 'AcFun', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://www.acfun.cn/v/ac...' },
    { id: 'meipai', name: '美拍', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://www.meipai.com/...' },
    { id: 'doupai', name: '逗拍', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://d.doupai.cc/...' },
    { id: 'quanminkge', name: '全民K歌', features: { video: true, images: false, audio: true }, badge: '原声', status: 'beta', parser: 'native', example: 'https://kg.qq.com/...' },
    { id: 'sixroom', name: '六间房', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://v.6.cn/...' },
    { id: 'xinpianchang', name: '新片场', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://www.xinpianchang.com/...' },
    { id: 'lvzhou', name: '绿洲', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://oasis.weibo.cn/...' },
    { id: 'haokan', name: '好看视频', features: { video: true, images: false, audio: false }, badge: '原生', status: 'beta', parser: 'native', example: 'https://haokan.baidu.com/v?vid=...' },
  ];

  return new Response(JSON.stringify({ success: true, platforms }), {
    headers: {
      'Content-Type': 'application/json',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
